<?php
$DATABASE_SERVERNAME = "localhost";
$DATABASE_USERNAME = "root";
$DATABASE_PASSWORD = "";

$DATABASE_NAME_TH = "vpay_th";
$DATABASE_NAME_TH_TABLE_TRANSACTION = "transaction";
$DATABASE_NAME_TH_TABLE_GATEWAY = "mst_gateway";

$DATABASE_SERVERNAME_TH_CFT = "172.16.0.193:3306";
$DATABASE_USERNAME_TH_CFT = "office_read";
$DATABASE_PASSWORD_TH_CFT = "G2gRfh";

$DATABASE_NAME_TH_CFT = "sg_slave";
$DATABASE_NAME_TH_TABLE_CFT = "report_today";

$DATABASE_SERVERNAME_SG = "112.121.158.92:6606";
$DATABASE_USERNAME_SG = "ops_ws";
$DATABASE_PASSWORD_SG = "L3sZtXjQNMP6ifxFnI";

$DATABASE_NAME_SG = "vpay";
$DATABASE_NAME_SG_TABLE = "topup_tab";

?>
